export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const SIGN_IN_CONFIRMATION = 'SIGN_IN_CONFIRMATION'
export const SIGN_IN_CONFIRMATION_SUCCESS = 'SIGN_IN_CONFIRMATION_SUCCESS'
export const SIGN_IN_CONFIRMATION_FAILURE = 'SIGN_IN_CONFIRMATION_FAILURE'

export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
export const SIGN_UP_CONFIRMATION = 'SIGN_UP_CONFIRMATION'
export const SIGN_UP_CONFIRMATION_SUCCESS = 'SIGN_UP_CONFIRMATION_SUCCESS'
export const SIGN_UP_CONFIRMATION_FAILURE = 'SIGN_UP_CONFIRMATION_FAILURE'

export const SET_IS_AUTHENTICATING = 'SET_IS_AUTHENTICATING'
export const SET_IS_AUTHENTICATING_WITHOUT_CODESENT_EFFECT =
  'SET_IS_AUTHENTICATING_WITHOUT_CODESENT_EFFECT'

export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'
export const IS_AUTHENTICATED_SUCCESS = 'IS_AUTHENTICATED_SUCCESS'
export const IS_AUTHENTICATED_FAILURE = 'IS_AUTHENTICATED_FAILURE'
export const REPLACE_USER_AND = 'REPLACE_USER_AND'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
